/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bmn.thrift.cs;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class serverConstants {

  public static final short BMN_VERSION = (short)3;

}
