/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bmn.thrift;


import org.apache.thrift.TEnum;

/**
 * Struct defined
 */
public enum BmnPartner implements TEnum {
  ALL(0),
  BAIDU(1),
  TENCENT(2),
  ALIBABA(3),
  LENOVO(4);

  private final int value;

  private BmnPartner(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BmnPartner findByValue(int value) { 
    switch (value) {
      case 0:
        return ALL;
      case 1:
        return BAIDU;
      case 2:
        return TENCENT;
      case 3:
        return ALIBABA;
      case 4:
        return LENOVO;
      default:
        return null;
    }
  }
}
