/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.bmn.thrift;


import org.apache.thrift.TEnum;

public enum ErrorCode implements TEnum {
  ALL(0),
  OK(1),
  FORCE_RECONNECT(2),
  FORCE_CLOSE(3);

  private final int value;

  private ErrorCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ErrorCode findByValue(int value) { 
    switch (value) {
      case 0:
        return ALL;
      case 1:
        return OK;
      case 2:
        return FORCE_RECONNECT;
      case 3:
        return FORCE_CLOSE;
      default:
        return null;
    }
  }
}
